name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-job:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore .NET workloads
        run: dotnet workload restore

      - name: Build project
        run: dotnet build

  analyze-code-with-preZero:
    name: Analyze Code with preZero
    runs-on: self-hosted
    needs: build-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install preZero CLI
        run: |
          brew install jq
          curl https://cdn.shiftleft.io/download/sl >/usr/local/bin/sl
          chmod a+rx /usr/local/bin/sl

      - name: Extract branch name
        id: extract_branch
        run: echo "branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Run preZero analysis
        run: |
          sl analyze \
            --app "${{ github.event.repository.name }}" \
            --tag branch=${{ steps.extract_branch.outputs.branch_name }} \
            --csharp DataMocker.sln
            --oss-project-dir /samples/DataMockerSample/DataMockerSample/DataMockerSample.csproj
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

  snyk-code-review-job:
    name: Snyk Code Review
    runs-on: self-hosted
    needs: build-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Snyk Code Test
        run: snyk code test --org=af5d509e-bed8-45d6-8f57-e92b4fca2d41
